### ISSUE TITLE
Error when Updating the skillset (01-azure-search)

### ISSUE THREAD

**Issue by Turochamp** [MicrosoftLearning/mslearn-knowledge-mining#16]
Does the lab need to be updated? Following the steps for _modify-search_ in _01-azure-search_ I get the error:

> Updating the skillset...
{"error":{"code":"","message":"Provided key is not a valid CognitiveServices type key for the region of your search service."}}
Waiting for 0 seconds, press CTRL+C to quit ...

Both the keys in skillset.json and modify-search.cmd are identical and taken from here:
![image](https://github.com/MicrosoftLearning/mslearn-knowledge-mining/assets/24321087/13029c92-75ca-4798-8be9-7063939e85bf)

**Comment by carlosarturoceron** [comment]
Hi @Turochamp , I had the same issue, please note that the key in skillset.json is not the same as the key in modify-search.cmd. The key in skillset.json comes from your Azure AI Multiservices Account/Keys and Endpoints.

Update the value in skillset.json with the right key and it should work.

**Comment by Turochamp** [comment]
Thanks @carlosarturoceron! That solved the issue.

**Comment by spotakash** [comment]
This one does not work. Even after adding right key, indexer is not adding up new Fields. Tried multiple time with no success, however execution of modify-search.cmd goes fine without any issue or error. It seems there is error in code or i am not sure. I have updated index.json, indexer.json and skillset.json with no success.
Curious question, how will cognitive multi service account will point to right ai search for skill set by just using key (we are not feeing endpoint detail anywhere for multi service account)

**Comment by dhaksr** [comment]
I hit the same issue as above.  The skillset.json dont have any key fields.  When I try to add the key field in the json, i hit error as . How to resolve above problem?

![image](https://github.com/MicrosoftLearning/mslearn-knowledge-mining/assets/24365447/97988e8c-3d68-48a8-8c32-4bd4663f9401)

**Comment by milciogh** [comment]
I had the same problem, for some reason i didn't know, the solution for me was to change the region of the resource group(it was on eastus) and that solve the problem
