### ISSUE TITLE
Error in create-search.cmd

### ISSUE THREAD

**Issue by carlosarturoceron** [MicrosoftLearning/mslearn-knowledge-mining#17]
Hi, looks like Labfiles\02-search-skill\create-search\skillset.json contains a custom skillset definition that is deprecated. And results in error when creating the search.

`Some of the skills defined in this skillset have been deprecated, and eventually any invocation of these skills will result in errors. Please update your skillset to use the latest version of these skills to avoid indexer downtime. [Learn more](https://go.microsoft.com/fwlink/p/?linkid=2170613)`

**Comment by dave-007** [comment]
This is still happenning, I may have a fix, can you reopen this issue, I can submit a PR for change to skillset.json to use the udpated skill and remove json attributes that are no longer supported by Microsoft.Skills.Text.V3.EntityRecognitionSkill

**Comment by dave-007** [comment]
PR submitted.

**Comment by ivorb** [comment]
fixed with merged PR
