### ISSUE TITLE
Error Labfiles 02-search-skill - Deprecated skills

### ISSUE THREAD

**Issue by pradorodriguez** [MicrosoftLearning/mslearn-knowledge-mining#18]
Some skills are deprecated in the following Lab:

- Error: Problem when running script "create-search.cmd"
- Lab: 02-search-skill
- Directory: mslearn-knowledge-mining/Labfiles/02-search-skill/
- File causing the error: skillset.json
- Deprecated skill: Microsoft.Skills.Text.EntityRecognitionSkill
- Evidence: https://learn.microsoft.com/en-us/azure/search/cognitive-search-skill-entity-recognition
  -The Entity Recognition skill (v2) (Microsoft.Skills.Text.EntityRecognitionSkill) is now discontinued replaced by [Microsoft.Skills.Text.V3.EntityRecognitionSkill](https://learn.microsoft.com/en-us/azure/search/cognitive-search-skill-entity-recognition-v3). Follow the recommendations in [Deprecated skills](https://learn.microsoft.com/en-us/azure/search/cognitive-search-skill-deprecated) to migrate to a supported skill.
- Supported skill: Microsoft.Skills.Text.V3.EntityRecognitionSkill
- Website: https://learn.microsoft.com/en-us/azure/search/cognitive-search-skill-entity-recognition-v3

**Comment by ivorb** [comment]
looks like the same issue as #17 - I'll investigate
