### ISSUE TITLE
Issue with querying an indexed search solution

### ISSUE THREAD

**Issue by bteleuca** [MicrosoftLearning/mslearn-knowledge-mining#19]
I ran into an issue with my [Exercise on creating a search solution](https://github.com/MicrosoftLearning/mslearn-knowledge-mining/blob/main/Instructions/Exercises/01-azure-search.md#query-the-modified-index). After indexing, querying the search with a select filter {"search": "London", "select": "url,sentiment,keyphrases", "filter": "metadata_author eq 'Reviewer' and sentiment eq 'positive'"} resulted in the error: _"Invalid expression: Could not find a property named 'url' on type 'search.document'. Parameter name: $select_". Consequently, the flask app returned the same error.

**Comment by ivorb** [comment]
this works fine in my instance. Are you confident the indexing was completed? if removing URL from the select statement, does it work?

**Comment by hariscats** [comment]
I encountered the same error. After removing the `'url'` and `'sentiment'` skills in the select parameter (of the search method), it worked for me.

**Comment by ivorb** [comment]
@afelix-95 can you run through this, and see if the prior script is causing issues? Or if `url` no longer exists how the instructions expect?

**Comment by afelix-95** [comment]
The problem is that in the instructions, the `language` index field is defined only as **Retrievable** and **Filterable**, while in the `index.json` it's also defined as **Searchable**. That makes the index update fail and not add the `sentiment` and `url` fields. To fix the issue, we need to select  **Searchable** for the `language` field when customizing the index in the Azure portal.

**Comment by jainharsh88** [comment]
Still facing the error in the query.

![Image](https://github.com/user-attachments/assets/b0837160-3f45-4320-9f3d-c40aceb543a0)

![Image](https://github.com/user-attachments/assets/1f2e2830-fc5d-42de-87bb-4c890c4ad2ed)

**Comment by ivorb** [comment]
@jainharsh88 what is the error you're getting? your screenshots don't indicate that. Have you confirmed you have pulled down the latest, if you've run this in the past?
