### ISSUE TITLE
'Deploy to Azure' button for 08-exercise-debug-search-issues.html fails to execute.

### ISSUE THREAD

**Issue by tsweatman1** [MicrosoftLearning/mslearn-knowledge-mining#22]

**Comment by tsweatman1** [comment]
Clicking the 'Deploy to Azure' button in exercise 8, for "Debug Search issues" fails to execute.  After clicking the 'Deploy to Azure' button, a new browser tab opens to display the .svg file of the 'Deploy to Azure' button.

**Comment by rhabenbacher** [comment]
I had exactly the same issue.

**Comment by ivorb** [comment]
I'll investigate in the next sprint

**Comment by loglux** [comment]
**This issue has been unresolved since March! It's unacceptable!**
there is an explanation of the issue and the fix
https://github.com/MicrosoftLearning/mslearn-knowledge-mining/issues/20

**Comment by ivorb** [comment]
The issue here and in 7 are fundamentally different. I'll address them as soon as I can

**Comment by ivorb** [comment]
github pages build appears to handle this differently since originally authored. removed image in favor of link, which successfully deployed.
