### ISSUE TITLE
Ex. 01 - Error: Existing field 'metadata_storage_name' cannot be changed.

### ISSUE THREAD

**Issue by sergio-usma** [MicrosoftLearning/mslearn-knowledge-mining#24]
https://github.com/MicrosoftLearning/mslearn-knowledge-mining/blob/e24cd8f3453193755a0bfeda315b51407103b06b/Labfiles/01-azure-search/modify-search/index.json#L215

Hi! Dear MSLearn team, I love your job! Thanks 🫡

In the line 215 of ./Labfiles/01-azure-search/modify-search/index.json it's needed to add "standard.lucene" in "analyzer" key in order the index don't generate the error:
```
-----
Updating the index...
{"error":{"code":"OperationNotAllowed","message":"Existing field 'language' cannot be changed.","details":[{"code":"CannotChangeExistingField","message":"Existing field 'language' cannot be changed."}]}}   
Waiting for 0 seconds, press CTRL+C to quit ...
-----
```

**Comment by ahmedsza** [comment]
thanks @sergio-usma . That helped me. I also needed to set "searchable": true in line 213

**Comment by ivorb** [comment]
updated
