### ISSUE TITLE
Missing "AI Services" tab in "08-exercise-debug-search-issues" exercise

### ISSUE THREAD

**Issue by loglux** [MicrosoftLearning/mslearn-knowledge-mining#35]
When following the [Debug search issues exercise](https://microsoftlearning.github.io/mslearn-knowledge-mining/Instructions/Exercises/08-exercise-debug-search-issues.html) I am instructed to select the "AI Services" tab under the "Skillsets" section. However, in my Azure portal, the "AI Services" tab is not present (screenshot attached), preventing me from proceeding with the exercise.

<img width="797" alt="image" src="https://github.com/MicrosoftLearning/mslearn-knowledge-mining/assets/37578325/64253de7-a0c8-498e-8ff1-02dc4a591511">

I tried to fix this by clicking "Connect AI service," selecting the appropriate service, and pressing "Save," but nothing has changed.

![image](https://github.com/MicrosoftLearning/mslearn-knowledge-mining/assets/37578325/b88973cc-7a57-496e-aa9f-450a0d3612bb)

**Comment by loglux** [comment]
OK. is an interface change on the Portal

**Comment by loglux** [comment]
Oh no

Execution result
Status
Timed out
Error message
Indexing was stopped because the free skillset execution quota has been reached. When no cognitive services subscription is attached to a skillset, only 20 documents can be enriched at a time. To index more documents, attach a cognitive services subscription to your skillset. See https://aka.ms/cog-srch-attach for more information.
Datasource
hotels-sample
Target index
hotels-sample-index
Start
15/06/2024, 12:14:01
End
15/06/2024, 12:14:01
Docs succeeded
0/0
Errors/Warnings
0/0

**Comment by ivorb** [comment]
Appears to be a change in the studio after all, and if the quota is changed for F0 tiers, we may need to switch this lab to S0. Thanks for reporting, we'll have to investigate. @afelix-95 if you have time, lets see if it's just a UI update or using S0 tier that can work around this. If not, I'll update the lab to work

**Comment by afelix-95** [comment]
Just a UI update. After choosing the created AI service resource and running the indexer, it was able to index all 50 documents. From the error message, my guess is that the Free AI service resource might have been selected instead of the one created during the exercise.
