### ISSUE TITLE
Error when updating skillset

### ISSUE THREAD

**Issue by dhaksr** [MicrosoftLearning/mslearn-knowledge-mining#36]
As per given documentation - we have to provide **_AI Service_** key in skillset.json to execute the modify-search.cmd file. However, while executing modify-search.cmd I got an error that 
> 
code":"InvalidRequestParameter","message":"Invalid product.","details":[{"code":"InvalidKeyField","message":"Skillsets require a valid 'all-in-one' Cognitive Services key. Provided key is of type AIServices.S0.
> 

Upon directly going to explorer and attaching AI Service with skillset, it creates a  cognitiveallinone service
![image](https://github.com/MicrosoftLearning/mslearn-knowledge-mining/assets/24365447/e6219da4-8351-4c47-9d66-00d7ca256a4c)

Pl note that it ends with suffix as  https://xxxxx.cognitiveservices.azure.com/. Where as AI service ends with https://xxxxxl.openai.azure.com/

So looks like there is an error in the documentation (or a new category of service is added)

Even after doing this, I get the following error. (I have used location as EAST US for Storage, Search, AI and Cognitive AI services

{"error":{"code":"","message":"Provided key is not a valid CognitiveServices type key for the region of your 
search service."}}
Waiting for 0 seconds, press CTRL+C to quit ...
-----
Updating the index...
{"error":{"code":"OperationNotAllowed","message":"Existing field 'metadata_author' cannot be changed.","details":[{"code":"CannotChangeExistingField","message":"Existing field 'metadata_author' cannot be changed."}]}} 
Waiting for 0 seconds, press CTRL+C to quit ...
-----
Updating the indexer...
{"error":{"code":"","message":"Output field mapping specifies target field 'sentiment' that doesn't exist in 
the index"}}-----
Resetting the indexer

**Comment by ivorb** [comment]
@afelix-95 can you try this lab (lab 2)? If the service changed under us let me know, I'll have to snap to the new way it works asap

**Comment by afelix-95** [comment]
Yeah I got the same error regarding the AI Service Key. Now instead of creating an Azure AI Services resource, we need to create an Azure AI services multi-service account. As for the second error, I had it as well when creating the resources in East US, but it was ok with West Europe.

**Comment by ivorb** [comment]
I expect the region issue is intermittent, thanks for verifying @afelix-95! Merged the PR to address this clarifying the AI Services resource. @dhaksr let us know if the issue still persists in a different region (try East US 2, for example)

**Comment by saspey** [comment]
For anyone finding the same issue, I can confirm you need to create an Azure AI Services Multi-Service Account and use the key from that service in the skillset.json file, **not** a Azure AI Service.
