### ISSUE TITLE
Query strings need trimming at the start

### ISSUE THREAD

**Issue by richeney** [MicrosoftLearning/mslearn-knowledge-mining#4]
The code blocks for the query stringshave a space at the first character, so using the copy results in an error in Search Explorer:

> "The request is invalid. Details: The parameter ' search' in the request payload is not a valid parameter for the operation 'search'."

Removing the space gives the expected result. Ideally the portal would TrimStart the query string, but is there a way to generate the static web page without the space at the start?

Affects:

1. Lab01
    - [Search the Index](https://microsoftlearning.github.io/mslearn-knowledge-mining/Instructions/Labs/01-azure-search.html#search-the-index)
1. Lab02
    - [Search the Index](https://microsoftlearning.github.io/mslearn-knowledge-mining/Instructions/Labs/02-search-skills.html#create-a-search-solution) (pre-custom skill)
    - [Search the Index](https://microsoftlearning.github.io/mslearn-knowledge-mining/Instructions/Labs/02-search-skills.html#search-the-index-1) (post-custom skill)

Great labs by the way!

**Comment by ivorb** [comment]
This should now be fixed, thanks for reporting!
