### ISSUE TITLE
Create a Custom Skill for Azure AI Search - Hosting plan missing for Function App, UI changes

### ISSUE THREAD

**Issue by mkennten** [MicrosoftLearning/mslearn-knowledge-mining#45]
In the exercise "Create a Custom Skill for Azure AI Search" (02-search-skills) the hosting plan for the Azure Function App is not specified. It should be "Consumption".

The Function app configuration part needs to be updated since the UI has changed a lot.

1. There is no "Publish" option in the consumption model anymore.
2. No "Setup a development environment" anymore, instead the user needs to click "Create Function"

**Comment by ivorb** [comment]
Fixed
