### ISSUE TITLE
Lab 2: EntityRecognitionSkill deprecated , v3 needed

### ISSUE THREAD

**Issue by unaihuete93** [MicrosoftLearning/mslearn-knowledge-mining#46]
We need to update the EntityRecognitionSkill to v3, is gives error to many learners https://learn.microsoft.com/en-us/azure/search/cognitive-search-skill-deprecated#microsoftskillstextentityrecognitionskill 

![image](https://github.com/user-attachments/assets/8ce638af-a82c-4017-9a9c-26f34723e76f)

Something similar to this makes it work
```

{
			"@odata.type": "#Microsoft.Skills.Text.V3.EntityRecognitionSkill",
			"name": "#1",
			"description": null,
			"context": "/document/merged_content",
			"categories": [
				"Person",
				"Quantity",
				"Organization",
				"URL",
				"Email",
				"Location",
				"DateTime"
			],
			"defaultLanguageCode": "en",
			"minimumPrecision": null,
			"inputs": [
				{
					"name": "text",
					"source": "/document/merged_content"
				},
				{
					"name": "languageCode",
					"source": "/document/language"
				}
			],
			"outputs": [
				{
					"name": "locations",
					"targetName": "locations"
				}
			]
		}

```

**Comment by VincentK16** [comment]
@unaihuete93 , thanks for reporting this.

**Comment by j-d-harvey** [comment]
Confirming seeing the same issue and @unaihuete93 suggestion worked

**Comment by VireshDoshi** [comment]
I can also confirm that the suggestion worked

**Comment by ivorb** [comment]
Fixed with most recent PR merged
