### ISSUE TITLE
AI-102-12 (CSS): Create a Custom Skill for Azure AI Search (JA)   EntityRecognitionSkill

### ISSUE THREAD

**Issue by DaddyCherry** [MicrosoftLearning/mslearn-knowledge-mining#48]
EntityRecognitionSkill is deprecated, so using /create-search will result in an error. To continue with the lab, you can deprecate or remove the target skill as a workaround.

**Instruction procedure location**
https://github.com/MicrosoftLearning/mslearn-knowledge-mining/blob/main/Instructions/Exercises/02-search-skills.md
In the terminal pane for the create-search folder, enter the following command run the batch script.

**Files and locations to be modified**
https://github.com/MicrosoftLearning/mslearn-knowledge-mining/blob/main/Labfiles/02-search-skill/create-search/skillset.json
Line:34        "@odata.type": "#Microsoft.Skills.Text.EntityRecognitionSkill",

**Comment by DaddyCherry** [comment]
Thank you.
I confirmed it works well.

**Comment by ivorb** [comment]
fixed with most recent PR
