### ISSUE TITLE
AI-102-12 Change #Microsoft.Skills.Text.EntityRecognitionSkill to #Microsoft.Skills.Text.V3.EntityRecognitionSkill

### ISSUE THREAD

**Issue by sakkuru** [MicrosoftLearning/mslearn-knowledge-mining#51]
This issue is related to MicrosoftLearning/mslearn-knowledge-mining#48. 
In addition to creating the skillset, it is also necessary to use #Microsoft.Skills.Text.V3.EntityRecognitionSkill when updating the skillset.

Specifically, the following file needs to be updated:

update-skillset.json
https://github.com/MicrosoftLearning/mslearn-knowledge-mining/blob/main/Labfiles/02-search-skill/update-search/update-skillset.json

**Comment by ivorb** [comment]
fixed
